server:
  port: 2003

################## spring ###############
spring:
  application:
    name: seata-account-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/seata_account
    username: bryan
    password: password


################# mybatis #################
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.bryan.cloud.entities
  configuration:
    map-underscore-to-camel-case: true


################ seata #####################
seata:
  registry:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      namespace: public
      group: SEATA_GROUP
      application: seata-server
  tx-service-group: default_tx_group # 事务组，由它获取TC服务的集群名称
  service:
    vgroup-mapping:
      default_tx_group: default # 事务组与TC服务集群的映射关系
  data-source-proxy-mode: AT


############### logging ######################
logging:
  level:
    io:
      seata: info
