server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
        service-name: ${spring.application.name}
        heartbeat:
          enabled: true
    gateway:
      routes:
        - id: pay_route1                   # 路由ID，保持唯一
#          uri: http://localhost:8001      # 匹配后的路由地址
          uri: lb://cloud-payment-service
          predicates:
            - Path=/pay/gateway/get/**     # 断言，路径匹配的请求进行路由
#            - After=2024-07-18T12:25:33.473697037+08:00[Asia/Shanghai]    # After在指定时间之后可以访问
#            - Before=2024-07-18T12:32:33.473697037+08:00[Asia/Shanghai]   # Before在指定时间之前可以访问
#            - Between=2024-07-18T13:38:00.473697037+08:00[Asia/Shanghai],2024-07-18T13:39:00.473697037+08:00[Asia/Shanghai]
#            - Cookie=username,testuser
#            - Header=X-Request-Id, \d+
#            - Host=**.bryan.com
#            - Query=userid, \d+
#            - RemoteAddr=192.168.0.1/24
#            - Method=GET

        - id: pay_route2
          uri: lb://cloud-payment-service
#          uri: http://localhost:8001
          predicates:
            - Path=/pay/gateway/info/**
#            - My=gold
#            - name: aaMy
#              args:
#                userType: gold

        - id: pay_route3
          uri: lb://cloud-payment-service
          predicates:
            - Path=/pay/gateway/filter
#            - Path=/gateway/filter
#            - Path=/XYZ/abc/{segment}
          filters:
#            - AddRequestHeader=X-Request-bryan1,bryan1Value       # 添加请求头
#            - AddRequestHeader=X-Request-bryan2,bryan2Value
#            - RemoveRequestHeader=sec-fetch-site                  # 删除响应头
#            - SetRequestHeader=Bryan-Custom-Header,bryan3Value    # 修改请求头
#            - AddRequestParameter=customerId,1919810              # 添加请求参数
#            - RemoveRequestParameter=customerName                 # 删除请求参数
#            - AddResponseHeader=X-Response-Bryan,bryan1Response   # 添加响应头
#            - SetResponseHeader=Date,2099-11-11                   # 修改响应头
#            - RemoveResponseHeader=Content-Type                   # 删除响应头
#            - PrefixPath=/pay                                     # 给请求地址添加PrefixPath
#            - SetPath=/pay/gateway/{segment}
#            - RedirectTo=302, https://www.baidu.com/
            - My=bryan
