server:
#  port: 8007
  port: 8001

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/db2024
    username: bryan
    password: password
    druid:
      validation-query: SELECT 1;
  profiles:
    active: default

################ mybatis ################
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.bryan.cloud.entities
  configuration:
    map-underscore-to-camel-case: true

################ zipkin ################
#management:
#  zipkin:
#    tracing:
#      endpoint: http://127.0.0.1:9411/api/v2/spans
#  tracing:
#    sampling:
#      probability: 1.0 # 采样率
